-- Run this exactly as is in the Supabase SQL Editor to create your database!

CREATE TABLE public.leads (
    "id" bigint generated by default as identity not null,
    "file_name" text null,
    "firm_name" text null,
    "mobile_number" text null,
    "website" text null,
    "status" text null default 'Not Called'::text,
    "notes" text null,
    "created_at" timestamp with time zone not null default now()
);

-- Note: The id column is the primary key.
ALTER TABLE public.leads ADD CONSTRAINT leads_pkey PRIMARY KEY (id);
